import { test, expect } from '@playwright/test';
import fs from 'node:fs';
const bn = JSON.parse(fs.readFileSync(new URL('../web/locales/bn.json', import.meta.url), 'utf8'));
test('Bangla controls preserve product enum values, percentage inputs and workspace drafts', async ({ page }) => {
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await page.getByRole('button', { name: 'Explore demo workspace' }).click();
  await page.getByRole('button', { name: 'Accounts', exact: true }).click();
  await page.getByLabel('New workspace name').fill('Product usability QA');
  await page.getByRole('button', { name: 'Create separate workspace' }).click();
  await expect(page.locator('.workspace-switch strong')).toHaveText('Product usability QA');
  await page.getByRole('button', { name: 'Products', exact: true }).click();
  await page.getByRole('button', { name: 'Add product', exact: true }).click();
  await page.getByLabel('Product name', { exact: true }).fill('Overview');
  await page.getByLabel('Category / niche', { exact: true }).selectOption('Other');
  await page.getByLabel('Your custom category').fill('Custom printed accessories');
  await page.getByLabel('Description', { exact: true }).fill('A custom printed accessory for everyday use.');
  await page.getByLabel('Expected failed / returned orders (%)', { exact: true }).fill('12');
  await page.getByRole('button', { name: 'Close dialog' }).click();
  await page.getByRole('button', { name: 'Add product', exact: true }).click();
  await expect(page.getByLabel('Product name', { exact: true })).toHaveValue('Overview');
  await expect(page.getByLabel('Your custom category')).toHaveValue('Custom printed accessories');
  await page.getByRole('button', { name: 'Close dialog' }).click();
  await page.getByRole('button', { name: 'বাংলায় দেখুন' }).click();
  await expect(page.locator('html')).toHaveAttribute('lang', 'bn');
  await page.getByRole('button', { name: bn['Add product'], exact: true }).click();
  await expect(page.getByLabel(bn['Product name'], { exact: true })).toHaveValue('Overview');
  await page.getByLabel(bn['Payment method'], { exact: true }).selectOption('prepaid');
  await page.getByLabel(bn['Desired profit margin (%)'], { exact: true }).fill('25');
  const response = page.waitForResponse(result => result.url().endsWith('/api/products') && result.request().method() === 'POST');
  await page.getByRole('dialog').getByRole('button', { name: bn['Add product'], exact: true }).click();
  const saved = await (await response).json();
  expect(saved.category).toBe('Custom printed accessories');
  expect(saved.name).toBe('Overview');
  expect(saved.paymentMethod).toBe('prepaid');
  expect(saved.costs.returnRate).toBe(0.12);
  expect(saved.desiredMargin).toBe(0.25);
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await expect(page.getByRole('heading', { name: 'Overview', exact: true })).toBeVisible();
  await page.reload();
  await expect(page.locator('html')).toHaveAttribute('lang', 'bn');
  await page.getByRole('button', { name: 'Switch to English' }).click();
  await expect(page.getByRole('heading', { name: 'Products & economics.' })).toBeVisible();
  expect(errors).toEqual([]);
});
test('research example and unfinished brief survive navigation and mobile Bangla has no horizontal overflow', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Explore demo workspace' }).click();
  await page.getByRole('button', { name: 'Research studio', exact: true }).click();
  await page.getByLabel('Start with a guided example').selectOption('ecommerce');
  await page.getByLabel('Offer / project name').fill('My custom ecommerce offer');
  await page.getByRole('button', { name: 'Products', exact: true }).click();
  await page.getByRole('button', { name: 'Research studio', exact: true }).click();
  await expect(page.getByLabel('Offer / project name')).toHaveValue('My custom ecommerce offer');
  await expect(page.getByLabel('What do you sell, and what problem does it solve?')).toHaveValue(/Custom ecommerce/);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: 'বাংলায় দেখুন' }).click();
  await expect(page.getByLabel(bn['Offer / project name'])).toHaveValue('My custom ecommerce offer');
  const dimensions = await page.evaluate(() => ({ width: document.documentElement.scrollWidth, viewport: innerWidth, font: getComputedStyle(document.querySelector('input')).fontSize }));
  expect(dimensions.width).toBeLessThanOrEqual(dimensions.viewport);
  expect(parseFloat(dimensions.font)).toBeGreaterThanOrEqual(16);
  await page.screenshot({ path: '.data/mobile-bangla.png', fullPage: true });
});
